### ISSUE TITLE
Switch csv parsing to csv library from binary-csv

### ISSUE THREAD

**Issue by rufuspollock** [okfn/json-table-schema-infer#2]
binary-csv has less support for options and file encodings (see #1 for a related bug). Propose we switch to standard node csv library.

**Comment by pwalsh** [comment]
I recommend closing based on https://github.com/frictionlessdata/jsontableschema-infer-js/issues/3

**Comment by rufuspollock** [comment]
WONTFIX. See #3 (deprecating this library).
