### ISSUE TITLE
Deprecate this library

### ISSUE THREAD

**Issue by pwalsh** [okfn/json-table-schema-infer#3]
See https://github.com/frictionlessdata/jsontableschema-js/issues/18

```
The new infer provides better type detection than the old, and supports more of the JTS spec. The only difference is that the new one does not handle opening of a CSV file: This is a purposeful design decision. We do not care where the stream or array of rows of data comes from as part of the infer process, so we leave it to the caller to take care of that.
```

I'd issue the deprecation notice myself, but I have no permissions on this library on npm.

**Comment by rufuspollock** [comment]
@pwalsh what is your username in npm?

Also we should get an "OK/OKI" username on npm and use it ;-) (and add these user ids to coding standards ...)

**Comment by pwalsh** [comment]
@rgrp 

I'm "pwalsh" on npm. We also do already have an "okfn" user on npm, and this is already in the coding standards docs for package publishing at OKI: https://github.com/okfn/coding-standards#package-publication

**Comment by rufuspollock** [comment]
@pwalsh your brilliance means you have anticipated my every suggestion (and i should re-read the coding standards!) 😄 🌟

**Comment by rufuspollock** [comment]
PS: you and okfn are now owners on npm. I'll leave you to close once you have deprecated there, added a deprecation notice here and moved the repo to oki-archive 😄

**Comment by pwalsh** [comment]
DONE.
